// Generated by tools/gen_rp6502_gfx.py -- do not edit.
#ifndef GFX_DATA_H
#define GFX_DATA_H
#include <stdint.h>

#define SPRITE_SLOTS 166
#define NUM_CHARS 64

extern const uint16_t STAMP2_SLOT[256];
extern const uint8_t STAMP2_CHUNKS[256];
extern const uint16_t STAMP1_SLOT[256];
extern const uint8_t STAMP1_CHUNKS[256];
extern const uint8_t STMPPALW[128];
extern const uint8_t CHARMAP[256];        // CSET1 char -> row table index
extern const uint8_t CHARROWS[NUM_CHARS * 24];  // 2 bytes x 12 rows
extern const uint16_t NTSC555[256];
#endif
